### ISSUE TITLE
Not able to clone project

### ISSUE THREAD

**Issue by AndresSepulveda** [dbuscombe-usgs/OpticalWaveGauging_DNN#1]
Hi, I am trying to clone the project but I get the following error

git clone --depth 1 git@github.com:dbuscombe-usgs/OpticalWaveGauging_DNN.git
Cloning into 'OpticalWaveGauging_DNN'...
Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 
Any ideas?

**Comment by ddbuscombe** [comment]
Are you using `ssh` or `https`? Try using the one you haven't

**Comment by ddbuscombe** [comment]
`git clone --depth 1 https://github.com/dbuscombe-usgs/OpticalWaveGauging_DNN.git`

**Comment by AndresSepulveda** [comment]
Thanks, https worked fine:

git clone --depth 1 https://github.com/dbuscombe-usgs/OpticalWaveGauging_DNN.git
Cloning into 'OpticalWaveGauging_DNN'...
remote: Enumerating objects: 11566, done.
remote: Counting objects: 100% (11566/11566), done.
remote: Compressing objects: 100% (11501/11501), done.
